language: python

python:
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"

env:
    - PYFLAKES_VERSION=pypi
    - PYFLAKES_VERSION=github

install:
    - if [ "$PYFLAKES_VERSION" == "github" ];
      then pip install git+https://github.com/pyflakes/pyflakes; fi
    - pip install .

script:
    - ./setup.py test
    - ./test_fuzz.py ./*.py

    - pyflakes ./*.py
    - pip install pycodestyle pydocstyle
    - pycodestyle ./*.py
    - pydocstyle autoflake.py setup.py

after_success:
    - pip install --quiet coverage
    - AUTOFLAKE_COVERAGE=1 coverage run --branch --parallel-mode --include='autoflake.py,test_autoflake.py' test_autoflake.py
    - coverage combine
    - coverage report --show-missing

    - pip install --quiet coveralls
    - coveralls
