language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"

env:
    - PYFLAKES_VERSION=pypi
    - PYFLAKES_VERSION=github

install:
    - if [ "$PYFLAKES_VERSION" == "github" ];
      then pip install git+https://github.com/pyflakes/pyflakes; fi
    - python setup.py --quiet install

script:
    - python test_autoflake.py
    - python test_acid.py test_acid.py

after_success:
    - pip install --quiet coverage
    - coverage run --include='autoflake.py,test_autoflake.py' test_autoflake.py
    - coverage report --show-missing

    - pip install --quiet coveralls
    - coveralls
