language: python

python:
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"

before_install:
    - pip --quiet install coverage

    # Install via apt-get since the standard pyflakes is Python 2 only.
    - sudo apt-get --quiet=2 install pyflakes

install:
    - python setup.py --quiet install

script:
    - python test_autoflake.py
    - coverage run test_autoflake.py
    - coverage report --show-missing
