language: python

python:
    - "2.7"
    - "3.2"
    - "3.3"

env:
    - PYFLAKES=''
    - PYFLAKES='apt-get'

before_install:
    - pip --quiet install coverage
    - if [ "$PYFLAKES" == "apt-get" ]; then sudo apt-get install --quiet=2 pyflakes; fi

install:
    - python setup.py --quiet install

script:
    - python test_autoflake.py
    - python test_acid.py test_acid.py
    - coverage run test_autoflake.py; true
    - coverage report --show-missing --omit='*/distutils/*'; true
